### ISSUE TITLE
Having Problem with pypdfocr on Windows 2008 R2

### ISSUE THREAD

**Issue by ahp38** [virantha/pypdfocr#49] opened 2016-08-11 16:14 UTC
Following is a list of errors when I try to use pypdfocr on Windows 2008 r2.

c:\PDFs>c:\python27\scripts\pypdfocr test.pdf
Starting conversion of test.pdf
'pdfimages' is not recognized as an internal or external command,
operable program or batch file.
WARNING: Could not execute pdfimages to calculate DPI (try installing xpdf or poppler?), so defaulting to 300dpi
Traceback (most recent call last):
  File "c:\python27\scripts\pypdfocr-script.py", line 9, in <module>
    load_entry_point('pypdfocr==0.9.0', 'console_scripts', 'pypdfocr')()
  File "c:\python27\lib\site-packages\pypdfocr\pypdfocr.py", line 492, in main
    script.go(sys.argv[1:])
  File "c:\python27\lib\site-packages\pypdfocr\pypdfocr.py", line 474, in go
    self._convert_and_file_email(self.pdf_filename)
  File "c:\python27\lib\site-packages\pypdfocr\pypdfocr.py", line 480, in _convert_and_file_email
    ocr_pdffilename = self.run_conversion(pdf_filename)
  File "c:\python27\lib\site-packages\pypdfocr\pypdfocr.py", line 359, in run_conversion
    hocr_filenames = self.ts.make_hocr_from_pnms(preprocess_imagefilenames)
  File "c:\python27\lib\site-packages\pypdfocr\pypdfocr_tesseract.py", line 130, in make_hocr_from_pnms
    uptodate,ver =  self._is_version_uptodate()
  File "c:\python27\lib\site-packages\pypdfocr\pypdfocr_tesseract.py", line 96, in _is_version_uptodate
    ver = [int(x) for x in ver_str.split('.')]
ValueError: invalid literal for int() with base 10: '00dev'

**Comment by dwmcqueen** [comment] 2016-08-11 16:55
This looks like a duplicate of #43

**Comment by virantha** [comment] 2016-10-11 17:12
Closed as dup.  thanks.

**Closed by virantha** 2016-10-11 17:12 UTC
