### ISSUE TITLE
Unable to process pdfs - Windows

### ISSUE THREAD

**Issue by fraserpage** [virantha/pypdfocr#43] opened 2016-04-20 20:35 UTC
I'm seeing the following on Windows 10. You assistance would be greatly appreciated. 

> Syntax Warning: Bad annotation destination
> Syntax Warning: Bad annotation destination 

I see about 30 lines of the above when using trying to process a pdf with pypdfocr filename.pdf.
I see the below with any usage.

> WARNING: Could not execute identify to calculate DPI (try installing imagemagick?), so defaulting to 300dpi
> Traceback (most recent call last):
>   File "<string>", line 495, in <module>
>   File "<string>", line 492, in main
>   File "<string>", line 474, in go
>   File "<string>", line 480, in _convert_and_file_email
>   File "<string>", line 359, in run_conversion
>   File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows\out00-PYZ.pyz\pypdfocr_tesseract", line 130, in make_hocr_from_pnms
>   File "C:\Users\Virantha Ekanayake\dev\pypdfocr\build\pypdfocr_windows\out00-PYZ.pyz\pypdfocr_tesseract", line 96, in _is_version_uptodate
> ValueError: invalid literal for int() with base 10: '00dev'

All dependencies are installed.

**Comment by flothesof** [comment] 2016-06-13 12:42
Hi @fraserpage 

I've had the same issue. In my case, the code for parsing the version string used by tesseract does not work as intended by the author. In particular, my version string was `3.05.00dev` which caused the same error as you when the script tried to parse it and determine whether it was correct. 

As a workaround, you can add the following bold lines to the file pypdfocr_tesseract.py found in python27\Lib\site-packages\pypdfocr:

```python
for line in ret_output.splitlines():
            if 'tesseract' in line:
                ver_str = line.split(' ')[1]
                **if ver_str.endswith('dev'):
                    ver_str = ver_str[:-3]**
```
Hope this helps,

Florian

**Comment by fraserpage** [comment] 2016-06-14 19:35
Thanks very much @flothesof! That got it working for me. 

I'm still seeing the warning about imagemagick. Any clues on that one?
`WARNING: Could not execute identify to calculate DPI (try installing imagemagick?), so defaulting to 300dpi`

**Comment by flothesof** [comment] 2016-06-14 21:58
Hey there!

The warning is normal, the program is just telling us it would like to do
some additional checks before adding ocr. I've found no problems with the
default resolution while using it.

Best regards
Florian

**Comment by fraserpage** [comment] 2016-06-15 14:45
Got it. Thanks for your help!

**Comment by virantha** [comment] 2016-06-23 18:10
Going to reopen and fix this in source for next release. Thanks for pointing this out, folks!

**Comment by dwmcqueen** [comment] 2016-08-11 16:54
Hi - can the exe be fixed with this same patch?

**Closed** 2016-10-11 18:54 UTC

**Comment by rasa** [comment] 2017-01-08 01:37
@flothesof: The warning message is actually not normal, but is reporting an error on Windows. This has been fixed in https://github.com/virantha/pypdfocr/pull/54

**Comment by qi55wyqu** [comment] 2017-11-08 01:56
I'm still running into this problem with the word _alpha_ in Version 0.9.1
My added fix for this (based on _flothesof_'s answer):
```python
checkFileEndings = ['dev', 'alpha']
for line in ret_output.splitlines():
    if 'tesseract' in line:
        ver_str = line.split(' ')[1]
        for fileEnding in checkFileEndings:
            if ver_str.endswith(fileEnding):
                ver_str = ver_str[:-len(fileEnding)]
```
